site_name: Template Repo
docs_dir: "doc"
repo_url: https://github.com/RomeroGabriel/template-repo
repo_name: RomeroGabriel/template-repo

nav:
  - Home: 
    - index.md
  - Examples:
    - Text: text.md
    - Code: code.md
    - Image: image.md

theme:
  name: material
  language: en
#   logo: images/
#   favicon: images/
  palette:
    scheme: slate
    primary: black
    accent: white
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.code.annotate

plugins:
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
